#!/bin/sh

#####################
#					#
#	Bspwm Config	#
#					#
#####################


# start/restart function
start() {
    killall $1
    $@ &
}

#
#   Startup background apps
#

# hotkeys
start sxhkd

# wallpaper
start feh --bg-scale /home/adam/Pictures/Wallpapers/leaf2.jpeg

# compositor
start picom --experimental-backends

# notifications
start dunst

# set default volume
start amixer set Master 50%

# pulseeffects daemon
start pulseeffects --gapplication-service

# polybar
start polybar main

# playerctl
start playerctld


#
#   Startup run commands
#

# xrandr set 165hz refresh rate
xrandr --output DP-4 --mode 1920x1080 --rate 164.92

# root window cursor
xsetroot -cursor_name left_ptr


#
#   Bspc
#

# desktops
bspc monitor -d I II III IV V VI VII VIII IX X

# border
bspc config focused_border_color "#aaaaaa"
bspc config normal_border_color  "#0f0f0f"

# windows
bspc config border_width          1
bspc config split_ratio           0.5
bspc config window_gap            4

# monocle
bspc config single_monocle        true
bspc config gapless_monocle       true
bspc config borderless_monocle    true

# control
bspc config focus_follows_pointer true
bspc config pointer_motion_interval 4