#! /bin/sh

#####################
#					#
#	Bspwm Config	#
#					#
#####################


# start/restart function
start() {
    killall $1
    $@ &
}

#
#   Startup
#

# hotkeys
start sxhkd

# wallpaper
start feh --bg-scale /home/adam/Pictures/matador-rocks.jpg

# compositor
start compton

# polybar
start polybar example -r

# notifications
start dunst

# root window cursor
start xsetroot -cursor_name left_ptr

# set default volume
start amixer set Master 50%

# pulseeffects daemon
start pulseeffects --gapplication-service

# xrandr (make sure to sudo nvidia-settings, x server configuration, advanced, force full compisition, save to x config)
start xrandr --output DP-2 --mode 1920x1080 --rate 164.92


#
#   Bspc
#

# desktops
bspc monitor -d I II III IV V VI VII VIII IX X

# border
bspc config normal_border_color  "#666666"
bspc config focused_border_color "#ffffff"

# windows
bspc config border_width          1
bspc config split_ratio           0.5
bspc config window_gap            12

# monocle
bspc config single_monocle        true
bspc config gapless_monocle       true
bspc config borderless_monocle    true

# control
bspc config focus_follows_pointer true
bspc config pointer_motion_interval 4ms