#!/bin/sh

#####################
#					#
#	Bspwm Config	#
#					#
#####################


# start/restart function
start() {
    killall $1
    $@ &
}

#
#   Startup background apps
#

# hotkeys
start sxhkd

# wallpaper
start feh --bg-scale ~/Pictures/wallpaper.jpg

# compositor
start picom

# notifications
start dunst

# pulseeffects daemon
start pulseeffects --gapplication-service

# polybar
start polybar main

# playerctl
start playerctld

# configure touchpad
start ~/.config/script/touchpad.sh

# xrandr set 165hz refresh rate
# (enable force full composition in nvidia-settings)
# xrandr --output DP-4 --mode 1920x1080 --rate 164.92

# glava and conky
start glava -d
sleep 1
start conky -d

# conky album art
pkill conky_album_art
~/.config/script/conky_album_art.sh &


#
#   Startup run commands
#

# starting volume
pactl set-sink-volume @DEFAULT_SINK@ 50%

# root window cursor
xsetroot -cursor_name left_ptr


#
#   Bspc
#

# desktops
bspc monitor -d I II III IV V VI VII VIII IX X

# border
bspc config focused_border_color "#aaaaaa"
bspc config normal_border_color  "#0f0f0f"

# windows
bspc config border_width          1
bspc config split_ratio           0.5
bspc config window_gap            8

# monocle
bspc config single_monocle        true
bspc config gapless_monocle       true
bspc config borderless_monocle    true

# control
bspc config focus_follows_pointer true
bspc config pointer_motion_interval 4