#!/bin/bash

#
#   Shell options
#

shopt -s direxpand


#
#   Env
#

export GOPATH="$HOME/Programming/Go"
export JAVA_HOME=/usr/lib64/openjdk-8
export QT_QPA_PLATFORMTHEME=qt5ct


#
#   Path
#

export PATH=$PATH:$GOPATH/bin:$JAVA_HOME/bin


#
#   Prompt
#

blue='\033[01;35m'
lblue='\033[01;36m'
clear='\033[0m'
export PS1="\[${blue}\]\W \[${clear}\]\$ "


#
#   Aliases
#

alias ls='exa -stype' # sort alphabetically and by type
alias ll='exa -stype -l' # the same, with more detail
alias lr='exa -rsmod' # list recently modified files, newest first
alias open='xdg-open'


#
#   Applications
#

alias code='detach code-oss'
alias teams='detachx flatpak run com.microsoft.Teams'
alias colpick='detachx gcolor3'
alias mc='detachx minecraft-launcher'
alias files='detach nautilus'
alias filesx='detachx nautilus'


#
#   Locations
#

docs="$HOME/Documents"
pics="$HOME/Pictures"
vids="$HOME/Videos"
music="$HOME/Music"
uni="$HOME/Uni"
prog="$HOME/Programming"
dls="$HOME/Downloads"
cfg="$HOME/.config"

alias home='cdr "$HOME"'
alias docs='cdr "$docs"'
alias pics='cdr "$pics"'
alias vids='cdr "$vids"'
alias music='cdr "$music"'
alias uni='cdr "$uni"'
alias prog='cdr "$prog"'
alias dls='cdr "$dls"'
alias cfg='cdr "$cfg"'


#
#   Functions
#

# change directory and show some recently modified files
function cdr() {
  cd "$1"
  pwd
  echo ''
  echo -e "${lblue}Recently modified:${clear}"
  lr --color=always | head
  echo ''
}

# run process detached
function detach() {
  ("$@" >/dev/null 2>&1 &)
}

# run process detached then exit
function detachx() {
  detach "$@" && exit > /dev/null 2>&1
}

# convert to pdf - use: topdf myfile.docx
function topdf() {
  lowriter --convert-to pdf "$@"
}

# open in firefox - use: goto example.com
function goto() {
  for x in "$@"; do
    detach firefox "$x"
  done
}

# search google in firefox - use: search "web development"
function search() {
  if [ "$1" != "" ]; then
    q=$(echo "$1" | sed s/" "/+/g)
    detachx firefox https://www.google.co.uk/search?q="$q"
  fi
}

# remove spaces from filenames - use: rmspaces *.pdf
function rmspaces() {
  for f in "$@"; do
    dir=$(dirname "$f")
    bn=$(basename "$f")
    bnFormatted=$(echo "$bn" | tr " " _)

    mv "$f" "$dir"/$bnFormatted
  done
}

# zip directories - use: zipdir mydir myotherdir
function zipdir() {
  for f in "$@"; do
    zip -r "$f" "$f"
  done
}

# lamp restart
function lampr() {
  sudo systemctl restart httpd php-fpm mariadb
}

# lamp stop
function lampstop() {
  sudo systemctl stop httpd php-fpm mariadb
}

# trim video - use: trim video.mp4 00:00:30 00:00:05 (filename, start timestamp, length of video)
function trim() {
  ffmpeg -ss $2 -i "$1" -t $3 -vcodec copy -acodec copy "trimmed-$1"
}

# convert to webm - use: towebm inputfile.mp4 outputfilename
function towebm() {
  ffmpeg -i "$1" "$2".webm
}

# get volume
function vol() {
  amixer -D pulse sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }'
}

# increase volume
function volup() {
  amixer -q sset Master 5%+
}

# decrease volume
function voldown() {
  amixer -q sset Master 5%-
}